# Generated by Django 4.1.5 on 2023-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_1', '0002_estado_producto_delete_comprar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_producto',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dni',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
